[[stc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f393d7dd978c7db122f5306d858227ab1b2ea2f9"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[stc.download]]
    sha256 = "3bf660d841824eea83c94958182186e803ccd7e786c7c3fbd34a0a1a3ecaab68"
    url = "https://github.com/ShaderTranspiler/stc/releases/download/v0.9.0-rc.1/stc_jll.v0.9.0-rc.1.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[stc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bdeb8c6294b149345a186e7f49e367b5b71a18d"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[stc.download]]
    sha256 = "0ce05c8848b97f8fc3d676101867a85d695da114ebace92160ad777cc811bfdc"
    url = "https://github.com/ShaderTranspiler/stc/releases/download/v0.9.0-rc.1/stc_jll.v0.9.0-rc.1.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[stc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ff20ccd0a4c86a883fea747d454b80a628298ce"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[stc.download]]
    sha256 = "5fb2151dde453a73bea463730a74a69da8031aba84f073fe65e49e353be25596"
    url = "https://github.com/ShaderTranspiler/stc/releases/download/v0.9.0-rc.1/stc_jll.v0.9.0-rc.1.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[stc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b3ba81038124ceb78b52ceaed88cc4632ca8a32"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[stc.download]]
    sha256 = "ce24c91b03b2405add0b7a2923ae68fb1235635b2b0c8bdad82d47c9768a2c63"
    url = "https://github.com/ShaderTranspiler/stc/releases/download/v0.9.0-rc.1/stc_jll.v0.9.0-rc.1.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[stc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b446bbf8ab3c0262a7d066dae38c86ddf8238147"
julia_version = "1.12.0"
os = "windows"

    [[stc.download]]
    sha256 = "40e116d1241cbf165ee4e198d596e290dd6b89bfdba3cd7a3fa5132f03c12fe9"
    url = "https://github.com/ShaderTranspiler/stc/releases/download/v0.9.0-rc.1/stc_jll.v0.9.0-rc.1.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[stc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af45150fa99d3de77674e00414a2477ae2aa3f20"
julia_version = "1.13.0"
os = "windows"

    [[stc.download]]
    sha256 = "99755a30d7643c52acb480e0198a88faa53a271884bc1cb824a47785d72dcd88"
    url = "https://github.com/ShaderTranspiler/stc/releases/download/v0.9.0-rc.1/stc_jll.v0.9.0-rc.1.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
