# Autogenerated wrapper script for stc_jll for aarch64-linux-gnu-cxx11-julia_version+1.10.0
export libstc, stc_cli

using Fmt_jll
JLLWrappers.@generate_wrapper_header("stc")
JLLWrappers.@declare_library_product(libstc, "libstc.so.0")
JLLWrappers.@declare_executable_product(stc_cli)
function __init__()
    JLLWrappers.@generate_init_header(Fmt_jll)
    JLLWrappers.@init_library_product(
        libstc,
        "lib/libstc.so",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        stc_cli,
        "bin/stc_cli",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
