# Autogenerated wrapper script for stc_jll for x86_64-w64-mingw32-cxx11-julia_version+1.12.0
export libstc, stc_cli

using Fmt_jll
JLLWrappers.@generate_wrapper_header("stc")
JLLWrappers.@declare_library_product(libstc, "libstc.dll")
JLLWrappers.@declare_executable_product(stc_cli)
function __init__()
    JLLWrappers.@generate_init_header(Fmt_jll)
    JLLWrappers.@init_library_product(
        libstc,
        "bin\\libstc.dll",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        stc_cli,
        "bin\\stc_cli.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
